[build]
  command = "npm run build"
  publish = "dist/client" # keep this for static assets

[functions]
  directory = "netlify/functions" # make sure functions are output here

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
